### ISSUE TITLE
Clarify CivicActions Accessibility Content - Site, Handbook, & GoogleDocs

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#29]
Clarify the relationship between the [CivicActions Handbook](https://handbook.civicactions.com/) & the [CivicActions Accessibility](https://civicactions.github.io/accessibility/) site. Also pull in or retire other resources such as [Early Draft Handbook](https://docs.google.com/document/d/1_zbP87VHT_XMOAyER0gNhNFSvYfcsnR13lMxOo8nEi4/edit?usp=sharing). 

Related issue https://github.com/CivicActions/accessibility/issues/35

**Comment by mgifford** [comment]
I think we should rename the **Handbook** https://civicactions.github.io/accessibility/handbook to something like **External Resources** We already have a CA Handbook with information about accessibility.  The CA Handbook is being built as the single source of truth. https://handbook.civicactions.com/en/latest/search.html?q=accessibility

**Comment by lukefretwell** [comment]
@mgifford if the primary handbook is going to be maintained consistently with accessibility items, then I agree that making handbook.civicactions.com the SSO. Currently, I don't think that page is being maintained but in general the handbook is still very difficult to navigate. 

So, I'm good with just linking to the accessibility page (or primary page) on the CivicActions handbook and not building anything out here. Rather than call it 'External resources' I would just put everything in the handbook and link to it.

**Comment by mgifford** [comment]
I am starting to think that maybe the CivicActions Handbook should be our public, but approved internal process. For instance, if we want everyone to officially include installing the WAVE Toolbar or Accessibility Insights in onboarding, that should be done in the general handbook.  If we want to highlight accessibility issues that are bigger than CivicActions or we are promoting a "how we do" accessibility, maybe that can go on the CivicActions Accessibility Site.  

There are good reasons to have more oversight on the handbook as it is in many ways like a policy of the organization. But there should be links between them and clarity about why something is in the handbook vs why it is on the site.

**Comment by mgifford** [comment]
After talking with @grugnog I think we should have the CA handbook & the CA Accessibility site to be closely integrated. 

There is a little bit of accessibility everywhere in the handbook (that links to the CA Accessibility site), but there is a more comprehensive overview of in the CA Accessibility site, that links back to the handbook to ensure that there is consistency.

Someone onboarding would go through the handbook. Learn what they need to for their role.  Then at some point later perhaps dive into the CA Accessibility site if their role requires it.

**Comment by mgifford** [comment]
This needs to be documented on the CA Accessibility Site. More importantly we need to look at specifically where to weave the content we have together so that pieces don't get lost.

**Comment by jerseycheese** [comment]
On the topic of ...

> I think we should rename the Handbook https://civicactions.github.io/accessibility/handbook to something like External Resources

> I'm good with just linking to the accessibility page (or primary page) on the CivicActions handbook and not building anything out here. Rather than call it 'External resources' I would just put everything in the handbook and link to it.

I do see the value of keeping a more updated/curated list of tools & resources (here) on the CA a11y site, rather than the handbook, where it seems like we're trying to put bigger picture information that probably won't overwhelm "onboarders", or be outdated anytime soon. If it's up for a vote, I suppose I'd vote to rename what we have from "Handbook" to "External Resources" on the CA a11y site and keep the info where it is. :)

This is what I gather, to sum things up:

**[CA handbook](https://handbook.civicactions.com/)**
- comprehensive a11y overview (w/ links out to the CA a11y site for more in-depth info)
- role-based a11y overviews

**[CA Accessibility site](https://civicactions.github.io/accessibility/)**
- more specific information/resources/tools/guidance
- highlight accessibility issues that are bigger than CivicActions
- promoting a "how we do" accessibility

GoogleDocs 
- internal CivicActions correspondence

@todo for this issue (@mgifford please confirm this is the purpose of this ticket, and these would be the tasks?) :

- [ ] Confirm the intent for each (handbook, CA a11y site)
- [ ] Document the intent for each (handbook, CA a11y site) on CA a11y site
- [ ] Review Early Draft Handbook for any info than can be retained, mark it as such, create issue to migrate it wherever it should be

**Comment by mgifford** [comment]
Documentation is going to be important here.  We PR's to the CA Handbook I think.

**Comment by jerseycheese** [comment]
> Documentation is going to be important here. We PR's to the CA Handbook I think.

Yep, another reason I think to move certain kinds of information to the CA a11y site, it removes a barrier to contribution if we're managing our own PRs.

**Comment by jerseycheese** [comment]
We now have dedicated issues for updating/auditing/drafting content in separate efforts, so I think this can be closed.

CA Handbook: https://github.com/CivicActions/accessibility/issues/35
Early Draft Handbook: https://github.com/CivicActions/accessibility/issues/85

**Comment by lukefretwell** [comment]
Thank you @jerseycheese! 🧀
